<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [

            [
                'key'           => 'business_models',
                'label'         => 'Business Models (Master List)',
                'value'         => json_encode(['B2B', 'B2C', 'Revenue-Share', 'Wholesale', 'Retail']),
                'default_value' => json_encode(['B2B', 'B2C', 'Revenue-Share', 'Wholesale', 'Retail']),
                'group'         => 'general',
                'type'          => 'json',
                'options'       => null,
                'description'   => 'Configurable master list of available business models (PRD Section 4).',
                'is_system'     => true,
            ],
            [
                'key'           => 'partner_approval_enabled',
                'label'         => 'Partner Approval Workflow',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'general',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'When enabled, new partners must go through Draft → Submitted → Under Review → Approved workflow before becoming Active.',
                'is_system'     => true,
            ],
            [
                'key'           => 'roi_methodology',
                'label'         => 'ROI Calculation Methodology',
                'value'         => 'net_profit_over_investment',
                'default_value' => 'net_profit_over_investment',
                'group'         => 'general',
                'type'          => 'select',
                'options'       => ['net_profit_over_investment', 'gross_profit_over_investment', 'revenue_over_investment'],
                'description'   => 'Formula used to calculate Partner ROI % (PRD Section 34). Default: Net Profit / Total Investment × 100.',
                'is_system'     => true,
            ],
            [
                'key'           => 'default_currency',
                'label'         => 'Default Currency',
                'value'         => 'BDT',
                'default_value' => 'BDT',
                'group'         => 'general',
                'type'          => 'string',
                'options'       => null,
                'description'   => 'Currency used across all financial displays.',
                'is_system'     => true,
            ],
            [
                'key'           => 'date_format',
                'label'         => 'Date Display Format',
                'value'         => 'd M Y',
                'default_value' => 'd M Y',
                'group'         => 'general',
                'type'          => 'select',
                'options'       => ['d M Y', 'Y-m-d', 'd/m/Y', 'm/d/Y'],
                'description'   => 'Format for displaying dates across the system.',
                'is_system'     => true,
            ],


            [
                'key'           => 'health_weight_financial',
                'label'         => 'Financial Health Weight (%)',
                'value'         => '25',
                'default_value' => '25',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Weight of Financial Health in the Partner Health Score. All weights must total 100.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_weight_revenue_growth',
                'label'         => 'Revenue Growth Weight (%)',
                'value'         => '20',
                'default_value' => '20',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Weight of Revenue Growth in the Partner Health Score.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_weight_profitability',
                'label'         => 'Profitability Weight (%)',
                'value'         => '20',
                'default_value' => '20',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Weight of Profitability in the Partner Health Score.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_weight_payment_behavior',
                'label'         => 'Payment Behavior Weight (%)',
                'value'         => '10',
                'default_value' => '10',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Weight of Payment Behavior in the Partner Health Score.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_weight_bandwidth_growth',
                'label'         => 'Bandwidth Growth Weight (%)',
                'value'         => '10',
                'default_value' => '10',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Weight of Bandwidth Growth in the Partner Health Score.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_weight_customer_growth',
                'label'         => 'Customer Growth Weight (%)',
                'value'         => '10',
                'default_value' => '10',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Weight of Customer Growth in the Partner Health Score.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_weight_operational',
                'label'         => 'Operational Performance Weight (%)',
                'value'         => '5',
                'default_value' => '5',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Weight of Operational Performance in the Partner Health Score.',
                'is_system'     => true,
            ],

            [
                'key'           => 'health_threshold_excellent',
                'label'         => 'Excellent Threshold (min score)',
                'value'         => '90',
                'default_value' => '90',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Score ≥ this value = Excellent status.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_threshold_healthy',
                'label'         => 'Healthy Threshold (min score)',
                'value'         => '75',
                'default_value' => '75',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Score ≥ this value = Healthy status.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_threshold_watch',
                'label'         => 'Watch Threshold (min score)',
                'value'         => '60',
                'default_value' => '60',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Score ≥ this value = Watch status.',
                'is_system'     => true,
            ],
            [
                'key'           => 'health_threshold_risk',
                'label'         => 'Risk Threshold (min score)',
                'value'         => '40',
                'default_value' => '40',
                'group'         => 'health',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Score ≥ this value = Risk status. Below = Critical.',
                'is_system'     => true,
            ],

            [
                'key'           => 'commission_default_rate_percent',
                'label'         => 'Default Commission Rate (%)',
                'value'         => '10',
                'default_value' => '10',
                'group'         => 'commission',
                'type'          => 'decimal',
                'options'       => null,
                'description'   => 'Default commission percentage when no specific rule is configured for a partner.',
                'is_system'     => true,
            ],
            [
                'key'           => 'commission_max_rate_percent',
                'label'         => 'Maximum Allowed Commission Rate (%)',
                'value'         => '30',
                'default_value' => '30',
                'group'         => 'commission',
                'type'          => 'decimal',
                'options'       => null,
                'description'   => 'No commission rule may exceed this percentage cap.',
                'is_system'     => true,
            ],
            [
                'key'           => 'commission_approval_required',
                'label'         => 'Commission Approval Required ',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'commission',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Commission must be approved before payment is allowed. Cannot be disabled.',
                'is_system'     => true,
            ],


            [
                'key'           => 'document_expiry_alert_days',
                'label'         => 'Document Expiry Alert Days',
                'value'         => json_encode([90, 60, 30, 15, 7]),
                'default_value' => json_encode([90, 60, 30, 15, 7]),
                'group'         => 'documents',
                'type'          => 'json',
                'options'       => null,
                'description'   => 'Days before document expiry to trigger alerts. PRD Section 72 defines: 90, 60, 30, 15, 7 days.',
                'is_system'     => true,
            ],
            [
                'key'           => 'document_max_size_mb',
                'label'         => 'Maximum Document Upload Size (MB)',
                'value'         => '10',
                'default_value' => '10',
                'group'         => 'documents',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Maximum allowed file size per document upload.',
                'is_system'     => true,
            ],
            [
                'key'           => 'document_allowed_types',
                'label'         => 'Allowed Document File Types',
                'value'         => json_encode(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']),
                'default_value' => json_encode(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']),
                'group'         => 'documents',
                'type'          => 'json',
                'options'       => null,
                'description'   => 'Permitted file extensions for document uploads. Executables (.exe, .php, .sh) are always blocked.',
                'is_system'     => true,
            ],


            [
                'key'           => 'bandwidth_change_types',
                'label'         => 'Bandwidth Change Types',
                'value'         => json_encode(['Upgrade', 'Downgrade', 'Temporary Upgrade', 'Suspension', 'Restoration']),
                'default_value' => json_encode(['Upgrade', 'Downgrade', 'Temporary Upgrade', 'Suspension', 'Restoration']),
                'group'         => 'bandwidth',
                'type'          => 'json',
                'options'       => null,
                'description'   => 'Configurable list of bandwidth change request types (PRD Section 41).',
                'is_system'     => true,
            ],
            [
                'key'           => 'bandwidth_approval_required',
                'label'         => 'Bandwidth Change Approval Required',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'bandwidth',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Bandwidth changes must follow the configured approval process.',
                'is_system'     => true,
            ],
            [
                'key'           => 'bandwidth_high_utilization_threshold',
                'label'         => 'High Utilization Alert Threshold (%)',
                'value'         => '80',
                'default_value' => '80',
                'group'         => 'bandwidth',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Trigger High Utilization notification when usage exceeds this percentage.',
                'is_system'     => true,
            ],
            [
                'key'           => 'equipment_warranty_alert_days',
                'label'         => 'Equipment Warranty Alert Days',
                'value'         => '30',
                'default_value' => '30',
                'group'         => 'bandwidth',
                'type'          => 'integer',
                'options'       => null,
                'description'   => 'Days before equipment warranty expiry to flag as a risk indicator.',
                'is_system'     => true,
            ],

            [
                'key'           => 'notify_partner_approval',
                'label'         => 'Notify: Partner Approval',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when partner is approved or rejected.',
                'is_system'     => true,
            ],
            [
                'key'           => 'notify_contract_expiry',
                'label'         => 'Notify: Contract Expiry',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when partner contract is nearing expiry.',
                'is_system'     => true,
            ],
            [
                'key'           => 'notify_credit_limit_exceeded',
                'label'         => 'Notify: Credit Limit Exceeded',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when partner outstanding exceeds credit limit.',
                'is_system'     => true,
            ],
            [
                'key'           => 'notify_payment_overdue',
                'label'         => 'Notify: Payment Overdue',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when partner payment becomes overdue.',
                'is_system'     => true,
            ],
            [
                'key'           => 'notify_bandwidth_high_utilization',
                'label'         => 'Notify: Bandwidth High Utilization',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when bandwidth utilization exceeds threshold.',
                'is_system'     => true,
            ],
            [
                'key'           => 'notify_equipment_warranty_expiry',
                'label'         => 'Notify: Equipment Warranty Expiry',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when equipment warranty is nearing expiry.',
                'is_system'     => true,
            ],
            [
                'key'           => 'notify_commission_pending_approval',
                'label'         => 'Notify: Commission Pending Approval',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when commission is generated and awaiting approval.',
                'is_system'     => true,
            ],
            [
                'key'           => 'notify_document_expiry',
                'label'         => 'Notify: Document Expiry',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when partner document is nearing or past expiry.',
                'is_system'     => true,
            ],
            [
                'key'           => 'notify_health_score_declined',
                'label'         => 'Notify: Health Score Declined',
                'value'         => 'true',
                'default_value' => 'true',
                'group'         => 'notifications',
                'type'          => 'boolean',
                'options'       => null,
                'description'   => 'Send notification when a partner\'s health score drops significantly.',
                'is_system'     => true,
            ],

        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('✅ SettingsSeeder: ' . count($settings) . ' settings seeded.');
    }
}
