<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $reportTitle }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 10px;
            color: #1e293b;
            margin: 0;
            padding: 15px;
        }
        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 12px;
            margin-bottom: 15px;
        }
        .logo-title {
            float: left;
        }
        .logo-title h1 {
            margin: 0;
            font-size: 18px;
            color: #1e3a8a;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .logo-title p {
            margin: 3px 0 0;
            color: #64748b;
            font-size: 10px;
        }
        .meta-info {
            float: right;
            text-align: right;
            font-size: 9px;
            color: #64748b;
        }
        .clear {
            clear: both;
        }
        .summary-cards {
            margin-bottom: 15px;
            width: 100%;
        }
        .summary-card {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 4px;
            padding: 8px 12px;
            display: inline-block;
            margin-right: 8px;
            margin-bottom: 6px;
        }
        .summary-card .label {
            font-size: 8px;
            color: #64748b;
            text-transform: uppercase;
            font-weight: bold;
        }
        .summary-card .value {
            font-size: 12px;
            font-weight: bold;
            color: #0f172a;
            margin-top: 2px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 9px;
        }
        th {
            background-color: #1e40af;
            color: #ffffff;
            font-weight: 600;
            text-align: left;
            padding: 6px 8px;
            border: 1px solid #1e3a8a;
            text-transform: uppercase;
            font-size: 8px;
            letter-spacing: 0.3px;
        }
        td {
            padding: 5px 8px;
            border: 1px solid #cbd5e1;
        }
        tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .badge {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-active { background-color: #dcfce7; color: #15803d; }
        .badge-pending { background-color: #fef9c3; color: #a16207; }
        .badge-danger { background-color: #fee2e2; color: #b91c1c; }
        .footer {
            margin-top: 25px;
            border-top: 1px solid #e2e8f0;
            padding-top: 8px;
            font-size: 8px;
            color: #94a3b8;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo-title">
            <h1>PLEXUS CLOUD</h1>
            <p>{{ $reportTitle }}</p>
        </div>
        <div class="meta-info">
            <p><strong>Generated At:</strong> {{ now()->format('d M Y, h:i A') }}</p>
            <p><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System Administrator' }}</p>
            <p><strong>Total Records:</strong> {{ count($data['rows'] ?? []) }}</p>
        </div>
        <div class="clear"></div>
    </div>

    <!-- Summary Statistics Cards -->
    @if(!empty($data['summary']))
    <div class="summary-cards">
        @foreach($data['summary'] as $key => $val)
            <div class="summary-card">
                <div class="label">{{ ucwords(str_replace('_', ' ', $key)) }}</div>
                <div class="value">
                    @if(str_contains($key, 'revenue') || str_contains($key, 'cost') || str_contains($key, 'profit') || str_contains($key, 'paid') || str_contains($key, 'outstanding') || str_contains($key, 'value'))
                        ৳{{ number_format((float)$val, 2) }}
                    @elseif(str_contains($key, 'pct') || str_contains($key, 'margin') || str_contains($key, 'rate'))
                        {{ number_format((float)$val, 1) }}%
                    @else
                        {{ is_numeric($val) ? number_format($val) : $val }}
                    @endif
                </div>
            </div>
        @endforeach
    </div>
    @endif

    <!-- Data Table -->
    <table>
        <thead>
            <tr>
                @foreach($data['columns'] as $col)
                    <th class="{{ in_array($col['format'] ?? '', ['currency', 'number', 'percentage', 'score']) ? 'text-right' : '' }}">
                        {{ $col['label'] }}
                    </th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($data['rows'] as $row)
                <tr>
                    @foreach($data['columns'] as $col)
                        @php
                            $val = $row[$col['key']] ?? '-';
                            $fmt = $col['format'] ?? 'string';
                        @endphp
                        <td class="{{ in_array($fmt, ['currency', 'number', 'percentage', 'score']) ? 'text-right' : '' }}">
                            @if($fmt === 'currency')
                                ৳{{ number_format((float)$val, 2) }}
                            @elseif($fmt === 'percentage')
                                {{ number_format((float)$val, 1) }}%
                            @elseif($fmt === 'number')
                                {{ number_format((float)$val) }}
                            @elseif($col['key'] === 'status')
                                <span class="badge {{ in_array(strtolower($val), ['active', 'approved', 'completed']) ? 'badge-active' : (in_array(strtolower($val), ['pending', 'watch']) ? 'badge-pending' : 'badge-danger') }}">
                                    {{ $val }}
                                </span>
                            @else
                                {{ $val }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($data['columns']) }}" class="text-center" style="padding: 15px; color: #94a3b8;">
                        No records found matching the criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Confidential — PLEXUS CLOUD Partner Management System &copy; {{ date('Y') }}. All rights reserved.
    </div>
</body>
</html>
